# Generated by Django 6.0 on 2025-12-13 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callbackrequest',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
